"""Simulation configuration defaults."""

import math

# Population & space
ENV_CAPACITY = 5_000

# World grid and terrain (closed cage)
FLOOR_COUNT = 3
FLOOR_HEIGHT = 25
GRID_WIDTH = 40
GRID_HEIGHT = FLOOR_COUNT * FLOOR_HEIGHT
HOUSING_DEPTH = 2
HOUSING_UNITS_PER_FLOOR = 100
PLATFORM_Z_STEP = 3.0

# Terrain codes
TERRAIN_VOID = 0
TERRAIN_PLATFORM = 1
TERRAIN_HOUSING = 2
TERRAIN_RESOURCE = 3

# Zones
ZONE_VOID = 0
ZONE_PLATFORM = 1
ZONE_HOUSING = 2
ZONE_RESOURCE = 3

# Render scaling (Panda3D) - small scale
RENDER_SCALE_XY = 3.0
RENDER_SCALE_Z = 3.0

# Agent render size (world units, pre-scale)
AGENT_RENDER_RADIUS = 0.35

# Housing visual
HOUSING_HEIGHT_OFFSET = 0.25

# Tile resources (food & water at top floor center)
TILE_FOOD_MAX = 100.0
TILE_WATER_MAX = 100.0
TILE_MATERIAL_MAX = 0.0
SOURCE_FOOD_PER_STEP = 10.0
SOURCE_WATER_PER_STEP = 10.0
RESOURCE_PATCH_RADIUS = 2
RATION_PILES_PER_DAY = 30

# Movement
MOVE_BASE_PROB = 0.2
MOVE_CURIOSITY_WEIGHT = 0.6
RESOURCE_SEEK_THRESHOLD = 10.0
GLOBAL_RESOURCE_SEEK = True

# Time
# 10,000 steps per sim day (5,000 day + 5,000 night)
STEP_MINUTES = 1
DAY_LENGTH_MINUTES = 5000
NIGHT_LENGTH_MINUTES = 5000
DAY_STEPS = 5000
NIGHT_STEPS = 5000
CYCLE_STEPS = DAY_STEPS + NIGHT_STEPS
YEAR_DAYS = 121.75
YEAR_STEPS = int(round(YEAR_DAYS * CYCLE_STEPS))

# Agent life cycle
MEDIAN_LIFESPAN_YEARS = 15.0
MAX_LIFESPAN_YEARS = 25.0
MEDIAN_AGE_STEPS = int(round(MEDIAN_LIFESPAN_YEARS * YEAR_STEPS))
MAX_AGE_STEPS = int(round(MAX_LIFESPAN_YEARS * YEAR_STEPS))
# Age at which reproduction can start (if other conditions are met)
MATURITY_AGE_YEARS = 2.0
MATURITY_AGE_STEPS = int(round(MATURITY_AGE_YEARS * YEAR_STEPS))
GESTATION_STEPS = 50
REPRO_COOLDOWN = 100

# Needs and metabolism
FOOD_SURVIVAL_DAYS = 14.0
WATER_SURVIVAL_DAYS = 3.0
ENERGY_DECAY = 1.0 / max(1.0, FOOD_SURVIVAL_DAYS * CYCLE_STEPS)
HYDRATION_DECAY = 1.0 / max(1.0, WATER_SURVIVAL_DAYS * CYCLE_STEPS)
FOOD_TO_ENERGY = 1.0
WATER_TO_HYDRATION = 1.0
SELF_REALIZATION_ENERGY_MIN = 0.6
SELF_REALIZATION_ENERGY_COST = 0.005
SOCIAL_REALIZATION_EMPATHY_GAIN = 0.002
SOCIAL_REALIZATION_BOND_GAIN = 0.01
CREATIVE_REALIZATION_WISDOM_GAIN = 0.002

# Heart and recovery
HEART_DECAY_BASE = 0.0002
HEART_DECAY_HUNGER = 0.001
HEART_DECAY_THIRST = 0.0015
HEART_DECAY_CROWDING = 0.001
HEART_RECOVERY = 0.0005

# Instinct thresholds
HUNGER_THRESHOLD = 0.5
THIRST_THRESHOLD = 0.5
MATE_ENERGY_THRESHOLD = 0.7
MATE_HYDRATION_THRESHOLD = 0.7
CRITICAL_ENERGY = 0.2
CRITICAL_HYDRATION = 0.2

# Carrying & sharing
WATER_CARRY_MAX = 2.0
WATER_CARRY_FILL_PER_STEP = 1.0
WATER_SHARE_THRESHOLD = 0.4
WATER_SHARE_AMOUNT = 0.5

# Scarcity & ideas
SCARCITY_WATER_PER_AGENT = 0.5
SCARCITY_FOOD_PER_AGENT = 0.5
IDEA_COOLDOWN_STEPS = 20
IDEA_PROB = 0.6
IDEA_ENGINEER_PROB = 0.3
IDEA_TRANSPORT_PROB = 0.3
IDEA_COORDINATE_PROB = 0.2
IDEA_MEMORY_PROB = 0.1
IDEA_TRADE_PROB = 0.1
ENGINEER_SOURCE_WATER = 5.0
ENGINEER_SOURCE_FOOD = 3.0

# Reproduction
ENCOUNTER_PROB = 0.15
CONCEPTION_PROB = 0.5

# Trait sampling
TRAIT_CORE_MIN = 0.6
TRAIT_CORE_MAX = 0.8
TRAIT_CORE_PROB = 0.9
MUTATION_STD = 0.03

# Wisdom and empathy
WISDOM_BASE = 0.1
WISDOM_COLOR_WEIGHT = 0.7
WISDOM_GROWTH_RATE = 0.002
EMPATHY_BASE = 0.1
EMPATHY_SHAPE_WEIGHT = 0.6
EMPATHY_GROWTH_RATE = 0.0015

# Personality traits (develop over life)
DEVELOPMENT_START = 0.5
CURIOSITY_GROWTH_RATE = 0.0015
SOCIALITY_GROWTH_RATE = 0.0015
RISK_GROWTH_RATE = 0.0015
AGGRESSION_GROWTH_RATE = 0.0015
CREATIVE_GROWTH_RATE = 0.0015
EXTRAVERSION_GROWTH_RATE = 0.0015
OPENNESS_GROWTH_RATE = 0.0015
CONSCIENTIOUSNESS_GROWTH_RATE = 0.0015
AGREEABLENESS_GROWTH_RATE = 0.0015
NEUROTICISM_GROWTH_RATE = 0.0015

# Genetics sampling (within parent range)
GENETIC_BIN = 0.02
GENETIC_DROP = 0.05
GENETIC_MIN_WEIGHT = 0.05

# Small lifetime drift (very slight)
TRAIT_DRIFT_STD = 0.0005

# Physical aging
PHYSICAL_DECLINE_START_YEARS = 10.0
PHYSICAL_DECLINE_MAX = 0.4

# Age mortality (median-based hazard)
AGE_MORTALITY_START_STEPS = MATURITY_AGE_STEPS
AGE_MORTALITY_RATE = math.log(2.0) / max(1, MEDIAN_AGE_STEPS)
AGE_MORTALITY_ACCEL = 4.0

# Sex labels (squares and circles)
SEX_A = "S"
SEX_B = "C"

# Social interactions and bonds
SOCIAL_INTERACTION_BASE = 0.01
SOCIAL_INTERACTION_SOCIALITY_WEIGHT = 0.05
SOCIAL_INTERACTION_EXTRAVERSION_WEIGHT = 0.05
BOND_INCREASE = 0.02
BOND_AGREEABLENESS_WEIGHT = 0.02
BOND_DECAY = 0.001
BOND_MIN = 0.01

# Accidental mortality
ACCIDENT_BASE_RATE = 0.00005
ACCIDENT_RISK_WEIGHT = 0.5
ACCIDENT_AGGRESSION_WEIGHT = 0.3
ACCIDENT_WISDOM_PROTECT = 0.2
ACCIDENT_CONSCIENTIOUSNESS_PROTECT = 0.2
ACCIDENT_NEUROTICISM_RISK = 0.2

# Behavior modifiers (personality)
MOVE_EXTRAVERSION_WEIGHT = 0.2
MOVE_OPENNESS_WEIGHT = 0.2
RESOURCE_SEEK_CONSCIENTIOUSNESS_BOOST = 5.0
NEED_THRESHOLD_NEUROTICISM_BIAS = 0.2

# Pathfinding performance
PATHFINDING_MAX_NODES = 400
